### ISSUE TITLE
mp3 misses a bit of sound at the end

### ISSUE THREAD

**Issue by ericoporto** [icculus/SDL_sound#27]
[playsound_simple_mp3.zip](https://github.com/icculus/SDL_sound/files/7190758/playsound_simple_mp3.zip)

I am attaching `playsound_simple.exe` built with the current SDL_sound and SDL2, and a really short `test.mp3` file. 

When playing this mp3 file on VLC there's a small bit more of sound you can listen, and when using `playsound_simple.exe` like

```
$> playsound_simple.exe test.mp3
Now playing [test.mp3]...
```

I can hear there's a small bit at the end that doesn't play.

**Comment by Ciastex** [comment]
The issue doesn't appear to be specific to the MP3 decoder - it also happens with this WAV: [doomsg.zip](https://github.com/icculus/SDL_sound/files/7776977/doomsg.zip), with an additional observation that the missing bit from the end is played at the beginning of the next playback. I am using SDL_sound in conjunction with SDL_nmix, but the behavior seems to be consistent with what @ericoporto has stated.

**Comment by sezero** [comment]
@icculus ?

**Comment by zelurker** [comment]
Particularly annoying on looping mp3, I don't seem to have the issue with ogg files though, and maybe the reason I don't have it with wav is simply because the wav has no compression... And sdl_sound is almost dead now ?

**Comment by zelurker** [comment]
Solution : take back the mp3 decoder used in sdl-1.2 (which used mpg123 instead of minimp3 here). I just did it for sdl2, it's not very hard to do, and it works. It requires to link libmpg123 of course, but it's easy to get, and it's better than having mp3 cut at the end.
It's actually mentioned in minimp3 readme that the end of the file can cause trouble. This thing is small and fast, but not really reliable... !

Ok problem fixed at least for me !

**Comment by icculus** [comment]
This turned out to be a silly bug in SDL_sound; it sets the EOF flag on the sample when it runs out of data to read in, but the MP3 decoder is not done processing the data at the same time, but that EOF flag stops the processing before it's done.

FLAC support had this problem too, presumably, so I applied the same fix there.

**Comment by zelurker** [comment]
Thanks for the fix, reverted to using this mp3 decoder then, but I'll keep
the one from sdl-1.2 in case it's useful again ! (apparently its only
drawback is that it requires libmpg123, but except that it's also very
fast, and size is not really an issue nowadays...).


Le ven. 25 mars 2022 à 07:16, Ryan C. Gordon ***@***.***> a
écrit :
