### ISSUE TITLE
support linking external libmodplug

### ISSUE THREAD

**Issue by rathann** [icculus/SDL_sound#42]
Please add an option to link against external libmodplug. Most Linux distributions include a libmodplug package that can be detected using pkg-config:
```cmake
find_package(PkgConfig)
pkg_check_modules(MODPLUG libmodplug)
```
Bundled libmodlug copy could be used if external one is not found.

**Comment by sezero** [comment]
The libmodplug version included here is a C-only conversion and its Init / Settings api is not compatible with mainstream. I think this should be closed as WONTFIX unless @icculus is feeling different.

**Comment by rathann** [comment]
Wouldn't it be less maintenance work for you to switch to external libmodplug? Not to mention that you're on the hook for fixing any security vulnerabilities in your libmodplug fork. libmodplug sources are larger than SDL_sound's. That seems to me like a good reason to unbundle. How much work would it be, anyway?

**Comment by icculus** [comment]
Explanation about removing external dependencies is here: https://www.patreon.com/posts/20211701

**Comment by ferdnyc** [comment]
@icculus 

> Explanation about removing external dependencies is here: https://www.patreon.com/posts/20211701

A reasonable argument. (And yes, I did read the whole thing. Well... the latter 2/3, once you got around to actually talking about SDL_sound, anyway.) I only have one quibble: You wrote...

> Some of SDL_sound's decoders were hand-written for the project, like the ones for [.wav files](https://hg.icculus.org/icculus/SDL_sound/file/df0f6c9a568e/src/SDL_sound_wav.c) or [Shorten audio](https://hg.icculus.org/icculus/SDL_sound/file/df0f6c9a568e/src/SDL_sound_shn.c), but others needed libvorbis, libspeex, libflac, ModPlug, MikMod, Timidity, etc, etc. Not only did you have to track down all these libraries yourself and hope they were compatible versions, but you had to comply with each library's license separately.

The idea that a user of SDL_sound **doesn't** have to comply with each library's license separately, just because that library is incorporated into SDL_sound, is AIUI very incorrect. Incorporating external code into SDL_sound doesn't convey the power to re-license it, so the original license still applies and, effectively, the licence for SDL_sound becomes **all** of the licenses for all of the included code.

At least, that's where the thinking from `fedora-legal` has evolved to: Packagers are even instructed, explicitly, [not to combine licenses or attempt to make any determinations about license "compatibility" or "effective" licenses](https://docs.fedoraproject.org/en-US/legal/license-field/#_no_effective_license_analysis), but to simply list _all_ of the licenses for every component of the binary package as an SPDX license expression.

I understand, of course, that licensing is far from the _only_ motivator, or even a _significant_ motivator, for incorporating dependencies into a project, and this isn't an attempt to change your stance on the issue... heck, I'm not even trying to argue that incorporating dependencies is the wrong approach. I just wanted to point out that, when it comes to issues of license compliance for bundled vs. separate code, the argument that incorporating code eliminates or reduces the user's burden of compliance is contrary to current guidance from `fedora-legal`.

**Comment by icculus** [comment]
Everything we're adding isn't just easily embeddable, it's public domain code.

(The remaining exception is timidity, which we're aiming to replace when I have time.)
